name = "CMU Courses"
slug = "cmucourses"
website-slug = "courses"
description = "Web application to browse course information and build schedules"
contributing-guide = """"
Reach out to Anish Pallati on Slack or an.ish on Discord for more information.
"""
maintainers = [
    "xavilien",
    "ap-1",
]
contributors = [
    "xavilien",
    "ap-1",
    "aparikh2",
]
repos = []
slack-channel-ids = [
]
remove-unlisted = false
sync-github = false
create-oidc-clients = true
secrets-population-layout = "none"
