name = "CMU Cal"
slug = "cmucal"
website-slug = "cal"
description = ""
contributing-guide = ""
maintainers = [
    "qianxuege",
]
contributors = [
    "qianxuege",
    "HeidiTao",
    "AliceeLe",
    "aparikh2",
]
repos = [
    "ScottyLabs/cmucal",
    "ScottyLabs/cmucal-backend",
]
slack-channel-ids = [
]
remove-unlisted = false
create-oidc-clients = false
secrets-population-layout = "none"
