slug = "cmucal"
name = "CMU Cal"
description = ""
website-slug = "cal"
leads = [
    "qianxuege",
]
devs = [
    "HeidiTao",
]
repos = [
    "ScottyLabs/cmucal",
]
slack-channel-ids = [
]
remove-unlisted = false
create-oidc-clients = false
secrets-population-layout = "none"
