slug = "cmueats"
name = "CMU Eats"
description = """
CMU Eats keep track of the statuses of the various dining locations across Carnegie
Mellon University. Quickly access the menus and specials at each location without
having to go through the arduous process of visiting the CMU Dining Website.
Live at cmueats.com.
"""
contributing-guide = """
Surely the CMU Eats leads will write the contributing guide here before you see this.
"""
maintainers = [
    "cirex-web",
    "laasyaaki"
]
contributors = [
    "cirex-web",
    "laasyaaki",
]
repos = [
    "ScottyLabs/cmueats",
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = false
create-oidc-clients = false
secrets-population-layout = "none"
