name = "CMU Eats"
slug = "cmueats"
description = """
CMU Eats keep track of the statuses of the various dining locations across Carnegie
Mellon University. Quickly access the menus and specials at each location without
having to go through the arduous process of visiting the CMU Dining Website.
Live at cmueats.com.
"""
contributing-guide = """
Want to contribute/join our team? Self-assign yourself to any github issue on either https://github.com/ScottyLabs/dining-api/issues or https://github.com/ScottyLabs/cmueats/issues and make a PR addressing the issue. (please ask
for clarifications if it's a substantial or very open-ended task! We don't want you to waste time working on something that isn't aligned with our project's general direction.)
"""
maintainers = [
    "cirex-web",
    "laasyaaki",
]
contributors = [
    "cirex-web",
    "laasyaaki",
    "michaeliuedu",
    "rohitkottomtharayil-tech"
]
repos = [
    "ScottyLabs/cmueats",
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = false
create-oidc-clients = false
secrets-population-layout = "none"
