name = "CMU Maps"
leads = [
    "Yuxiang-Huang",
    "tsurbs",
    "romycyy",
]
devs = [
    "JettChenT",
    "Nicolapps",
]
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
]
