name = "CMU Maps"
slug = "cmumaps"
website-slug = "maps"
description = """
CMU Maps is a web application that provides a map of the Carnegie Mellon University
campus, allowing users to easily access information about campus locations, live at cmumaps.com.
"""
contributing-guide = "https://github.com/ScottyLabs/cmumaps/blob/main/.github/CONTRIBUTING.md"
maintainers = [
    "Yuxiang-Huang",
    "tsurbs",
    "luke992",
    "ellylai",
    "romycyy",
    "JettChenT",
]
contributors = [
    # Year 2025-2026

    ## Tech Team
    "luke992",       # Web Team Lead
    "ellylai",       # Data Team Co-Lead
    "romycyy",       # Data Team Co-Lead
    "JettChenT",     # Backend Team Lead
    "Yuxiang-Huang", # Developer
    "tsurbs",        # Developer
    "Richard-31415", # Developer
    "SayeVikram",    #Developer
    "tu2463",        # Developer
    "lastlegume",    # Developer
    "Jc-965",        # Developer

    ## Design Team
    "Wunwan",          # Design Team Lead
    "JeffreyYijiWang", # Design Advisor
    "JessCai06",       # Designer

    # Year 2024-2025
    "Yuxiang-Huang",   # Tech Lead
    "JeffreyYijiWang", # Design Lead
    "luke992",         # Developer
    "romycyy",         # Developer
    "tsurbs",          # Developer

    # Year 2023-2024
    "tsurbs",          # Tech Lead
    "Yuxiang-Huang",   # Developer
    "JeffreyYijiWang", # Designer

    # Year 2022-2023
    "Nicolapps", # Founder
]
applicants = [
    "FarmerJohnsBessie",
]
repos = [
    "ScottyLabs/cmumaps",
    "ScottyLabs/secrets-sync-scripts", # Need access to use secrets sync scripts
]
slack-channel-ids = [
    "C05T7QRN4LF",
    "C09F81J8XUL",
]
