slug = "cmumaps"
name = "CMU Maps"
website-slug = "maps"
leads = [
    "Yuxiang-Huang",
    "tsurbs",
    "romycyy",
    "luke992",
]
devs = [
    "JettChenT",
    "Nicolapps",
]
applicants = [
]
ext-admins = [
]
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
    "C09F81J8XUL",
]
