name = "cmumaps"
leads = [
    "Yuxiang-Huang",
    "luke992",
]
devs = [
    "ellylai",
    "Nicolapps",
    "JettChenT",
    "SLin24",
]
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
]
