slug = "cmumaps"
name = "CMU Maps"
description = """
CMU Maps is a web application that provides a map of the Carnegie Mellon University
campus, allowing users to easily access information about campus locations, live at cmumaps.com.
"""
contributing-guide = "https://github.com/ScottyLabs/cmumaps/blob/main/.github/CONTRIBUTING.md"
website-slug = "maps"
maintainers = [
    "Yuxiang-Huang",
    "tsurbs",
    "luke992",
    "ellylai",
    "JettChenT",
]
contributors = [
    # Year 2025-2026
    "luke992",       # Web Team Lead
    "ellylai",       # Data Team Co-Lead
    "romycyy",       # Data Team Co-Lead
    "JettChenT",     # Backend Team Lead
    "Yuxiang-Huang", # Developer
    "tsurbs",        # Developer

    # Year 2024-2025
    "Yuxiang-Huang", # Tech Lead
    "luke992",       # Developer
    "romycyy",       # Developer
    "tsurbs",        # Developer

    # Year 2023-2024
    "tsurbs",        # Tech Lead
    "Yuxiang-Huang", # Developer

    # Year 2022-2023
    "Nicolapps", # Founder
]
applicants = [
]
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
    "C09F81J8XUL",
]
