slug = "cmumaps"
name = "CMU Maps"
description = """
CMU Maps is a web application that provides a map of the Carnegie Mellon University
campus, allowing users to easily access information about campus locations,
live at cmumaps.com.
"""
website-slug = "maps"
leads = [
    "Yuxiang-Huang",
    "tsurbs",
    "romycyy",
    "luke992",
]
devs = [
    "JettChenT",
    "Nicolapps",
]
applicants = [
]
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
    "C09F81J8XUL",
]
