name = "CMU Maps"
leads = [
    "Yuxiang-Huang",
    "tsurbs",
    "romycyy",
    "luke992",
]
devs = [
    "JettChenT",
    "Nicolapps",
]
admins = []
repos = [
    "ScottyLabs/cmumaps",
]
slack-channel-ids = [
    "C05T7QRN4LF",
    "C09F81J8XUL",
]
