slug = "cmusearch"
name = "CMU Search"
website-slug = "search"
description = """
CMU Search is a search engine to search for courses, locations, and events on campus.
Join if you love search engines! (not live yet)
"""
maintainers = [
    "tsurbs",
    "Yuxiang-Huang",
]
contributors = [
]
repos = [
    "ScottyLabs/cmusearch",
]
slack-channel-ids = [
]
create-oidc-clients = false
