name = "CMU Search"
slug = "cmusearch"
website-slug = "search"
description = """
CMU Search is a search engine to search for courses, locations, and events on campus.
Join if you love search engines!
"""
contributing-guide = """
DM Theo Urban on Slack for now until he finally finds this line ðŸ˜ˆ.
"""
maintainers = [
    "tsurbs",
    "Yuxiang-Huang",
]
contributors = [
    "tsurbs",
    "Yuxiang-Huang",
]
repos = [
    "ScottyLabs/cmusearch",
]
slack-channel-ids = [
]
create-oidc-clients = false
