slug = "cmusearch"
name = "CMU Search"
website-slug = "search"
leads = [
    "Yuxiang-Huang",
    "tsurbs",
]
devs = []
repos = [
    "ScottyLabs/cmusearch",
]
slack-channel-ids = [
]
create-oidc-clients = false
