slug = "governance"
name = "Governance"
# Leads are individuals who need the secrets for developing Governance features.
leads = [
    "Yuxiang-Huang",
]
# Devs are individuals who need permission to merge PRs to accept new contributors
# into teams. This includes tech leads and any subteam leads.
devs = []
repos = [
    "ScottyLabs/governance",
]
slack-channel-ids = [
]
create-oidc-clients = false
secrets-population-layout = "single"
