name = "Governance"
slug = "governance"
description = """
Governance defines the organizational structure and manages permissions for ScottyLabs teams.
Joining Governance means you want to work on the codebase inside the __meta/ directory.
"""
contributing-guide = "https://github.com/ScottyLabs/governance/blob/main/.github/CONTRIBUTING.md"
maintainers = [
    "Yuxiang-Huang",
]
contributors = [
    "Yuxiang-Huang",
]
applicants = [
]
repos = [
    "ScottyLabs/governance",
]
slack-channel-ids = [
]
create-oidc-clients = false
secrets-population-layout = "single"
