slug = "graph"
name = "Graph"
description = """
Graph has been turned into a testing site for the **new** auth system.
Do not join this team.
"""
website-slug = "graph"
leads = [
    "Yuxiang-Huang",
]
devs = []
repos = [
    "ScottyLabs/graph",
]
slack-channel-ids = [
    "C0A03GYAP3R",
]
