name = "Graph"
slug = "graph"
website-slug = "graph"
description = """A social graph visualization of ScottyLabs."""
contributing-guide = "DO NOT join this team yet!"
maintainers = [
    "Yuxiang-Huang",
]
contributors = [
    "Yuxiang-Huang",
]
repos = [
    # graph is not in ScottyLabs GitHub organization yet.
    # "ScottyLabs/graph",
]
slack-channel-ids = [
    "C0A03GYAP3R",
]

# graph uses a different Keycloak realm for Google sign-in.
create-oidc-clients = false
