slug = "graph"
name = "Graph"
description = """
Graph has been turned into a testing site for the **new** auth system.
"""
contributing-guide = "DO NOT join this team!"
website-slug = "graph"
maintainers = [
    "Yuxiang-Huang",
]
contributors = [
    "Yuxiang-Huang",
]
repos = [
    "ScottyLabs/graph",
]
slack-channel-ids = [
    "C0A03GYAP3R",
]
