name = "Internal Tooling"
slug = "internal-tooling"
description = """
Internal Tooling is a team that builds and maintains custom software to
empower our ScottyLabs members and broader CMU community to operate
efficiently and reliably.
"""
contributing-guide = """
Message Max Wen on Slack or tentype on Discord if you are interested in joining the team!
"""
maintainers = [
    "TenType",
    "ap-1",
    "Yuxiang-Huang", # Responsible for Secrets Sync Scripts
]
contributors = [
    "TenType",
    "ap-1",
    "Yuxiang-Huang",
    "maybe-yiyi",
    "sjskong",
]
repos = [
    "ScottyLabs/dalmatian",            # Discord bot for CMUCourses, CMUEats, and other ScottyLabs services
    "ScottyLabs/discord-verify",       # Discord verification for online CMU communities
    "ScottyLabs/doberman",             # Uptime monitor
    "ScottyLabs/cmu-guide",            # Guide to introduce first-year students to CMU
    "ScottyLabs/secrets-sync-scripts", # Scripts to sync secrets to Vault
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = true
create-oidc-clients = false
secrets-population-layout = "multi"
