slug = "leadership"
name = "Leadership"
description = "Leadership refers to the official ScottyLabs leadership team."
maintainers = [
    "Yuxiang-Huang",
]
contributors = [
    "Yuxiang-Huang",
]
repos = []
slack-channel-ids = [
]
sync-github = false
create-oidc-clients = false
secrets-population-layout = "none"
