name = "Leadership"
slug = "leadership"
description = "Leadership refers to the official ScottyLabs Tech leadership team."
contributing-guide = """
Join the ScottyLabs Tech leadership team by becoming the next
Director of ScottyLabs, Director of Technology, or Tech Lead!
"""
# The maintainers of Tech Leadership should only include
# the Director of ScottyLabs, Director of Technology, Head of DevOps,
# Tech Senior Advisors, and ScottyLabs GitHub Account.
maintainers = [
    "Yuxiang-Huang",  # Current Director of Technology
    "ap-1",
    "tsurbs",
    "xavilien",
    "scottylabs-bot",
]
contributors = [
    # Year 2025-2026
    "tsurbs",        # Director of ScottyLabs
    "Yuxiang-Huang", # Director of Technology
    "JackHurew",     # Head of Data & Analytics
    "ap-1",          # Head of DevOps
    "qianxuege",     # Tech Lead of CMU Cal
    "xavilien",      # Tech Co-Lead of CMU Courses
    "yl25946",       # Tech Co-Lead of CMU Courses
    "cirex-web",     # Tech Co-Lead of CMU Eats
    "laasyaaki",     # Tech Co-Lead of CMU Eats
    "luke992",       # Tech Co-Lead of CMU Maps
    "ellylai",       # Tech Co-Lead of CMU Maps
    "kath45823",     # Tech Lead of Corgi
    "cirex-web",     # Tech Lead of Flex
    "axgu",          # Tech Lead of Lost and Found
    "ap-1",          # Tech Lead of Terrier
    "TenType",       # Tech Lead of Internal Tooling
    "thesuperRL",    # Tech Lead of DevOps

    # Year 2024-2025
    "mzhou08",  # Director of ScottyLabs
    "xavilien", # Director of Technology

    # Year 2023-2024
    "Adrastopoulos", # Director of Technology

    # ScottyLabs GitHub Account
    "scottylabs-bot",
]
repos = []
slack-channel-ids = [
    "C08N23VR6RY", # Tech leads channel
]

# The leadership team does not need GitHub teams
sync-github = false

# The leadership team does not need OIDC clients
create-oidc-clients = false

# The leadership team does not need secrets population
secrets-population-layout = "none"
