name = "Lost and Found"
slug = "lost-and-found"
website-slug = "lost"
description = """
V3 Lost and Found Rewrite in Next (Copied from the repo description lol)
"""
contributing-guide = "DM Anna Gu on Slack for now."
maintainers = [
    "axgu",
]
contributors = [
    "axgu",
    "leonliu223",
    "theezanonymous"
]
repos = [
    "ScottyLabs/lost-and-found",
]
slack-channel-ids = [
]
remove-unlisted = false
sync-github = false

# Currently uses Clerk, so no OIDC clients needed.
create-oidc-clients = false

secrets-population-layout = "none"
