slug = "sl-ai"
name = "SLAI"
description = """
ScottyLabs AI team is responsible for cmuGPT, CMU Search, MCP server, and other
AI-related projects.
"""
contributing-guide = "DM Ellyse Lai on Slack for now."
maintainers = [
    "ellylai",
]
contributors = [
    "ellylai",
]
repos = [
    "ScottyLabs/cmugpt",

    # CMU Search is a search engine to search for courses, locations, and events on campus.
    # Join if you love search engines!
    "ScottyLabs/cmusearch",

    "ScottyLabs/mcp-server",
]
slack-channel-ids = [
    "C08SRUGUQ05",
]

# Remove this once the team is fully registered
remove-unlisted = false

# Remove this once the team is fully registered
sync-github = false

# The AI team does not need OIDC clients or secrets population for now.
create-oidc-clients = false
secrets-population-layout = "none"
