name = "SLAI"
slug = "sl-ai"
description = """
ScottyLabs AI team is responsible for cmuGPT, CMU Search, MCP server, and other AI-related projects.

cmuGPT: Chatbot with ability to integrate with our own applications (CMU Eats, CMU Maps, CMU Courses).
CMU Search: Our own search engine! Join if you love search engines!
MCP Server: Wraps our own APIs, as an MCP server, used by cmuGPT.
"""
contributing-guide = """
Our teams/projects are in the development phase.
If you love AI/ML and have experience or interest in working with RAG, LLMs, MCP, vector databases, APIs, etc, feel free to DM Ellyse Lai on Slack!
We also will probably need designers for frontend and help with backend, so if you have experience in these you are also welcome."""

maintainers = [
    "ellylai",
    "krishsaxena",
]
contributors = [
    "ellylai",
    "alanj268",
    "krishsaxena",
]
repos = [
    "ScottyLabs/cmugpt",

    # CMU Search is a search engine to search for courses, locations, and events on campus.
    # Join if you love search engines!
    "ScottyLabs/cmusearch",

    "ScottyLabs/mcp-server",
]
slack-channel-ids = [
    "C08SRUGUQ05",
    "U09DL6NH8FL",
]

# Remove this once the team is fully registered
remove-unlisted = false

# Remove this once the team is fully registered
sync-github = false

# The AI team does not need OIDC clients or secrets population for now.
create-oidc-clients = false
secrets-population-layout = "none"
